import 'store_class.dart';

List<Pet> catStoreItems = [
  Pet("Bingal Cat", "assets/images/bingalCat.png", 85.00,
      "Introducing the Bengal cat, a vibrant and enigmatic\n breed that captivates the hearts of cat lovers worldwide.\n With a striking coat pattern that ranges from \nthe classic black and white to the rare leopard spots, \nBengals are not only beautiful but also come with a unique \nset of characteristics."),
  Pet("Abyssinan Cat", "assets/images/abysCat.png", 100.00,
      "Abyssinians are known for their friendly and outgoing\n personalities, making them excellent companions for active families.\n They are highly social and can become bored if left alone for too long,\n so it's recommended to provide them with a companion cat or other pets. \nDespite their social nature, they are independent and enjoy a good amount of space \nto explore and play"),
  Pet("Burmese Cat", "assets/images/burmeseCat.png", 60.00,
      "Discover the Burmese cat, a breed that is known for its striking appearance and friendly demeanor. With a coat that is short and sleek, these cats come in a variety of colors, including silver, blue, and lilac, with the silver Burmese being the most common. Their faces are flat, and their eyes are almond-shaped, which gives them an exotic look "),
  Pet("Persian Cat", "assets/images/persianCat.png", 99.00,
      "Embark on a journey of luxurious companionship with the Persian cat, a breed known for its distinctive features and gentle nature. Persians are medium-sized felines with a flat face, big eyes, and a long, luxurious coat that can be white, silver, fawn, or black with a ticked pattern"),
  Pet("Russian Blue Cat", "assets/images/rusCat.png", 120.00,
      "Discover the elegance and charm of the Russian Blue cat, a breed that captivates with its striking blue-gray coat and expressive emerald-green eyes. This medium-sized feline is known for its distinctive upturned corners of the mouth, which give them a perpetual Mona Lisa-like smile. Their fine-boned legs and muscular bodies add to their graceful and firm demeanor"),
  Pet("Sphinx Cat", "assets/images/sphinxCat.png", 150.00,
      "Experience the enchanting allure of the Sphynx cat, a breed that has captivated hearts with its unique, hairless appearance and graceful demeanor. The Sphynx cat is a medium-sized feline with a sleek, muscular body that is dense and heavy for its size. Its striking features include wrinkled skin, large ears, and a coat that is completely hairless, giving it a sleek and smooth appearance"),
  Pet("Bingal Cat", "assets/images/bingalCat.png", 85.00,
      "Introducing the Bengal cat, a vibrant and enigmatic\n breed that captivates the hearts of cat lovers worldwide.\n With a striking coat pattern that ranges from \nthe classic black and white to the rare leopard spots, \nBengals are not only beautiful but also come with a unique \nset of characteristics."),
  Pet("Abyssinan Cat", "assets/images/abysCat.png", 100.00,
      "Abyssinians are known for their friendly and outgoing\n personalities, making them excellent companions for active families.\n They are highly social and can become bored if left alone for too long,\n so it's recommended to provide them with a companion cat or other pets. \nDespite their social nature, they are independent and enjoy a good amount of space \nto explore and play"),
  Pet("Burmese Cat", "assets/images/bingalCat.png", 60.00,
      "Discover the Burmese cat, a breed that is known for its striking appearance and friendly demeanor. With a coat that is short and sleek, these cats come in a variety of colors, including silver, blue, and lilac, with the silver Burmese being the most common. Their faces are flat, and their eyes are almond-shaped, which gives them an exotic look "),
  Pet("Persian Cat", "assets/images/persianCat.png", 99.00,
      "Embark on a journey of luxurious companionship with the Persian cat, a breed known for its distinctive features and gentle nature. Persians are medium-sized felines with a flat face, big eyes, and a long, luxurious coat that can be white, silver, fawn, or black with a ticked pattern"),
  Pet("Russian Blue Cat", "assets/images/rusCat.png", 120.00,
      "Discover the elegance and charm of the Russian Blue cat, a breed that captivates with its striking blue-gray coat and expressive emerald-green eyes. This medium-sized feline is known for its distinctive upturned corners of the mouth, which give them a perpetual Mona Lisa-like smile. Their fine-boned legs and muscular bodies add to their graceful and firm demeanor"),
  Pet("Sphinx Cat", "assets/images/sphinxCat.png", 150.00,
      "Experience the enchanting allure of the Sphynx cat, a breed that has captivated hearts with its unique, hairless appearance and graceful demeanor. The Sphynx cat is a medium-sized feline with a sleek, muscular body that is dense and heavy for its size. Its striking features include wrinkled skin, large ears, and a coat that is completely hairless, giving it a sleek and smooth appearance"),
];

List<Store> listOfPetStores = [
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems),
  Store("Cat Pet Store", "assets/images/sphinxCat.png", "Colon, Cebu City",
      catStoreItems)
];
